theme = "lc"
baseURL = "http://partylite.vo.llnwd.net/o15/u/USOLC/Learning_Center/LC_New/"
ignoreFiles = [ ".sass-cache" ]
enableRobotsTXT = true

### Language Config
defaultContentLanguage = "en"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
contentDir = "content-us"

# Google Analytics tracking ID
googleAnalytics = ""

uglyurls = false
canonifyURLS = true

[params]
  offsiteurl = false
  countrycode = "us"
  ## Fix this, especially when going live
  videodir = "http://partylite.vo.llnwd.net/o15/u/USOLC/Learning_Center/LC_Main/"
  locale = "en-US"
  copyright = "All rights reserved."
  backtocbc = "Back to CBC"
  relateddocuments = "Related Documents"

### Taxonomies ###
[taxonomies]
  category = "categories"
  series = "series"

### Begin Menu (English) ###
[languages.en]
  title = "Learning Center"
  weight = 0
  languageName = "English"
  languageCode = "en-US"
  logo = "images/lc-logo-usen.svg"
  logomark = "images/lc-logomark.svg"
  
  ### New Consultants ###
  [[languages.en.menu.main]]
    name = "New Consultants"
    identifier = "new-consultants"
    url = "/categories/new-consultants/index.html"
    weight = 10
    [[languages.en.menu.main]]
      name = "Host Program"
      parent = "new-consultants"
      url = "/categories/host-program/index.html"
    [[languages.en.menu.main]]
     name = "First Parties"
     parent = "new-consultants"
     url = "/categories/first-parties/index.html"
    [[languages.en.menu.main]]
      name = "Income & Rewards"
      parent = "new-consultants"
      url = "/categories/income-and-rewards/index.html"
    [[languages.en.menu.main]]
      name = "Find Your Signature"
      parent = "new-consultants"
      url = "/categories/find-your-signature/index.html"
  
  ### Selling and Booking ###
  [[languages.en.menu.main]]
    name = "Selling and Booking"
    identifier = "selling-and-booking"
    url = "categories/selling-and-booking/index.html"
    weight = 20
    [[languages.en.menu.main]]
      name = "Sell"
      parent = "selling-and-booking"
      url = "/categories/sell/index.html"
    [[languages.en.menu.main]]
      name = "Book"
      parent = "selling-and-booking"
      url = "/categories/book/index.html"

  ### Online Biz ###
  [[languages.en.menu.main]]
    name = "Online Biz"
    identifier = "Online Biz"
    weight = 30
    [[languages.en.menu.main]]
      name = "Your Consultant Website"
      parent = "Online Biz"
      url = "/categories/your-consultant-website/index.html"
    [[languages.en.menu.main]]
      name = "Social Networking"
      parent = "Online Biz"
      url = "/categories/social-networking/index.html"
    [[languages.en.menu.main]]
      name = "PartyLite Preferred"
      parent = "Online Biz"
      url = "/categories/partylite-preferred/index.html"
    
  ### Leader Academy ###
  [[languages.en.menu.main]]
    name = "Leader Academy"
    identifier = "leadership"
    weight = 50
    [[languages.en.menu.main]]
      name = "Leadership Skills"
      parent = "leadership"
      url = "/categories/leadership-skills/index.html"
      weight = -20
    [[languages.en.menu.main]]
      name = "Sponsoring"
      parent = "leadership"
      url = "/categories/sponsor/index.html"
      weight = -10

  ### Product ###
  [[languages.en.menu.main]]
    name = "Product"
    identifier = "Product"
    weight = 60
    [[languages.en.menu.main]]
      name = "Product Training"
      parent = "Product"
      url = "/categories/product-training/index.html"

  ### Party Ideas ###
  [[languages.en.menu.main]]
    name = "Party Ideas"
    identifier = "Party Ideas"
    weight = 70
    [[languages.en.menu.main]]
      name = "Find Your Signature Party"
      parent = "Party Ideas"
      url = "/categories/find-your-signature/index.html"
    [[languages.en.menu.main]]
      name = "Games"
      parent = "Party Ideas"
      url = "/categories/games/index.html"
