theme = "lc"
baseURL = "http://partylite.vo.llnwd.net/o15/u/CAOLC/Learning_Center_Canada/New/"
ignoreFiles = [ ".sass-cache" ]
enableRobotsTXT = true

### Language Config
defaultContentLanguage = "en"
# Renders the default content language in subdir, e.g. /en/. 
# The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
contentDir = "content-ca"

# Google Analytics tracking ID
googleAnalytics = ""

uglyurls = false
canonifyURLS = true

[params]
  offsiteurl = false
  countrycode = "ca"
  ## Fix this, especially when going live
  videodir = "http://partylite.vo.llnwd.net/o15/u/CAOLC/Learning_Center_Canada/English/LC_Main/"
  locale = "en-CA"
  copyright = "All rights reserved."
  backtocbc = "Back to CBC"
  pllogo = "images/partylite-logo.svg"

### Taxonomies ###
[taxonomies]
  category = "categories"
  series = "series"

### Begin Menu (English) ###
[languages.en]
  baseURL = "http://partylite.vo.llnwd.net/o15/u/CAOLC/Learning_Center_Canada/New/en/"
  title = "Learning Centre"
  navTitle = "images/lc-logo-caen-txt-inv.svg"
  weight = 0
  languageName = "English"
  languageCode = "en-CA"
  logo = "images/lc-logo-caen.svg"
  logomobile = "images/lc-logo-caen-ko.svg"
  logomark = "images/lc-logomark.svg"
  copyright = "All rights reserved."
  backtocbc = "Back to CBC"
  relateddocuments = "Related Documents"
  
  ### New Consultants ###
  [[languages.en.menu.main]]
    name = "New Consultants"
    identifier = "new-consultants"
    url = "/categories/new-consultants/index.html"
    weight = 10
    [[languages.en.menu.main]]
      name = "Host Program"
      parent = "new-consultants"
      url = "/categories/host-program/index.html"
    [[languages.en.menu.main]]
     name = "First Parties"
     parent = "new-consultants"
     url = "/categories/first-parties/index.html"
    [[languages.en.menu.main]]
      name = "Income & Rewards"
      parent = "new-consultants"
      url = "/categories/income-and-rewards/index.html"
    [[languages.en.menu.main]]
      name = "Find Your Signature"
      parent = "new-consultants"
      url = "/categories/find-your-signature/index.html"
  
  ### Selling and Booking ###
  [[languages.en.menu.main]]
    name = "Selling and Booking"
    identifier = "selling-and-booking"
    url = "categories/selling-and-booking/index.html"
    weight = 20
    [[languages.en.menu.main]]
      name = "Sell"
      parent = "selling-and-booking"
      url = "/categories/sell/index.html"
    [[languages.en.menu.main]]
      name = "Book"
      parent = "selling-and-booking"
      url = "/categories/book/index.html"

  ### Online Biz ###
  [[languages.en.menu.main]]
    name = "Online Biz"
    identifier = "Online Biz"
    weight = 30
    [[languages.en.menu.main]]
      name = "Your Consultant Website"
      parent = "Online Biz"
      url = "/categories/your-consultant-website/index.html"
    [[languages.en.menu.main]]
      name = "Social Networking"
      parent = "Online Biz"
      url = "/categories/social-networking/index.html"
    [[languages.en.menu.main]]
      name = "PartyLite Preferred"
      parent = "Online Biz"
      url = "/categories/partylite-preferred/index.html"
    
  ### Leader Academy ###
  [[languages.en.menu.main]]
    name = "Leader Academy"
    identifier = "leadership"
    weight = 50
    [[languages.en.menu.main]]
      name = "Leadership Skills"
      parent = "leadership"
      url = "/categories/leadership-skills/index.html"
      weight = -20
    [[languages.en.menu.main]]
      name = "Sponsoring"
      parent = "leadership"
      url = "/categories/sponsor/index.html"
      weight = -10

  ### Product ###
  [[languages.en.menu.main]]
    name = "Product"
    identifier = "Product"
    weight = 60
    [[languages.en.menu.main]]
      name = "Product Training"
      parent = "Product"
      url = "/categories/product-training/index.html"

  ### Party Ideas ###
  [[languages.en.menu.main]]
    name = "Party Ideas"
    identifier = "Party Ideas"
    weight = 70
    [[languages.en.menu.main]]
      name = "Find Your Signature Party"
      parent = "Party Ideas"
      url = "/categories/find-your-signature/index.html"
    [[languages.en.menu.main]]
      name = "Games"
      parent = "Party Ideas"
      url = "/categories/games/index.html"

### Begin Menu (French) ###
[languages.fr]
  baseURL = "http://partylite.vo.llnwd.net/o15/u/CAOLC/Learning_Center_Canada/fr/"
  title = "Centre de Formation"
  navtitle = "images/lc-logo-cafr-txt-inv.svg"
  weight = 0
  languageName = "French"
  languageCode = "fr-CA"
  logo = "images/lc-logo-cafr.svg"
  logomobile = "images/lc-logo-cafr-ko.svg"
  logomark = "images/lc-logomark.svg"
  copyright = "Tous droits réservés."
  backtocbc = "Retour au Centre d'Affaires"
  relateddocuments = "Documents Connexes"
  
  ### New Consultants ###
  [[languages.fr.menu.main]]
    name = "Nouvelles Conseillères"
    identifier = "new-consultants"
    url = "/categories/new-consultants/index.html"
    weight = 10
    [[languages.fr.menu.main]]
      ## Host Program ##
      name = "Encadrement Des Hôtesses"
      parent = "new-consultants"
      url = "/categories/programme-d'hôtesses-hôtes/index.html"
    [[languages.fr.menu.main]]
      ## First Parties ##
      name = "Vos premières présentations"
      parent = "new-consultants"
      url = "/categories/vos-premières-présentations/index.html"
    [[languages.fr.menu.main]]
      ## Income and Rewards ##
      name = "Revenu et récompenses"
      parent = "new-consultants"
      url = "/categories/revenu-et-récompenses/index.html"
    [[languages.fr.menu.main]]
      ## Find Your Signature ##
      name = "Find Your Signature"
      parent = "new-consultants"
      url = "/categories/find-your-signature/index.html"
  
  ### Selling and Booking ###
  [[languages.fr.menu.main]]
    name = "Ventes & Engagements"
    identifier = "selling-and-booking"
    url = "categories/selling-and-booking/index.html"
    weight = 20
    [[languages.fr.menu.main]]
      ## Selling ##
      name = "Ventes"
      parent = "selling-and-booking"
      url = "/categories/ventes/index.html"
    [[languages.fr.menu.main]]
      ## Booking ##
      name = "Engagements"
      parent = "selling-and-booking"
      url = "/categories/engagements/index.html"

  ### Online Biz ###
  [[languages.fr.menu.main]]
    name = "En Ligne"
    identifier = "Online Biz"
    weight = 30
    [[languages.fr.menu.main]]
      ## Your Consultant Website ##
      name = "Votre Site De Conseillère"
      parent = "Online Biz"
      url = "/categories/votre-site-de-conseillère/index.html"
    [[languages.fr.menu.main]]
      ## Social Networking ##
      name = "Réseaux Sociaux"
      parent = "Online Biz"
      url = "/categories/réseaux-sociaux/index.html"
    [[languages.fr.menu.main]]
      ## PartyLite Preferred ##
      name = "PartyLite Preferred"
      parent = "Online Biz"
      url = "/categories/partylite-preferred/index.html"
    
  ### Leader Academy ###
  [[languages.fr.menu.main]]
    name = "Leader Academy"
    identifier = "leadership"
    weight = 50
    [[languages.fr.menu.main]]
      ## Leadership Skills ##
      name = "Compétences En Leadership"
      parent = "leadership"
      url = "/categories/compétences-en-leadership/index.html"
      weight = -20
    [[languages.fr.menu.main]]
      ## Sponsoring ##
      name = "Parrainage"
      parent = "leadership"
      url = "/categories/parrainage/index.html"
      weight = -10

  ### Product ###
  [[languages.fr.menu.main]]
    name = "Produits"
    identifier = "Product"
    weight = 60
    [[languages.fr.menu.main]]
      ## Product Training ##
      name = "Formation Produits"
      parent = "Product"
      url = "/categories/formation-produits/index.html"

  ### Party Ideas ###
  [[languages.fr.menu.main]]
    name = "Idées Présentations"
    identifier = "Party Ideas"
    weight = 70
    [[languages.fr.menu.main]]
      ## Find Your Signature Party ##
      name = "Présentations de Find Your Signature"
      parent = "Party Ideas"
      url = "/categories/find-your-signature/index.html"
    [[languages.fr.menu.main]]
      ## Games ##
      name = "Jeux"
      parent = "Party Ideas"
      url = "/categories/jeux/index.html"
