# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Learning Center"
license = "MIT"
licenselink = "https://github.com/gulrenor/pllc/blob/master/themes/lc/LICENSE.md"
description = "PartyLite's Learning Center 2016 Redesign"
homepage = "http://partylite.vo.llnwd.net/o15/u/USOLC/Learning_Center/index.html"
min_version = 0.17

[author]
  name = "Tim Harrison"
  homepage = "http://www.twharrison.com"
